version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:11.8-alpine
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - data-volume:/data/db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: App
    networks: [postgres]
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4:4.24
    ports:
      - '8089:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - /data/pgadmin:/root/.pgadmin
    networks: [postgres]
volumes:
  data-volume:
networks:
  postgres:
    driver: bridge